# Vi mode
bindkey -v
export EDITOR="vim"
setopt extendedglob
setopt nocaseglob
setopt AUTO_CD

# Language
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# XDG
export XDG_CONFIG_HOME="$HOME/.config/"

#
# ZPLUG
#
export ZPLUG_HOME=${HOME}/.zplug

# install zplug if required
if ! [[ -d ${ZPLUG_HOME} ]] then
    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh| zsh
fi

# Load zplug (https://github.com/zplug/zplug)
source ${ZPLUG_HOME}/init.zsh

# FIXME: this is not working properly.  Problems with PATH variable (pointing
# to bin dir with no binaries)  just pull by hand time to time
# To manage zplug itself like other packages
# I will try just forcing ${ZPLUG_HOME} into the path
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# Plugins to be installed
zplug "zdharma/history-search-multi-word"
zplug "zsh-users/zsh-completions"
zplug "b4b4r07/enhancd", use:init.sh
zplug "b4b4r07/zsh-vimode-visual", use:"*.zsh", defer:3

zplug "zsh-users/zsh-history-substring-search", defer:3
if zplug check 'zsh-users/zsh-history-substring-search'; then
    bindkey -M vicmd 'k' history-substring-search-up
    bindkey -M vicmd 'j' history-substring-search-down
fi

#zplug 'b4b4r07/zsh-history', as:command, use:misc/fzf-wrapper.zsh, rename-to:ff
#if zplug check 'b4b4r07/zsh-history'; then
#    export ZSH_HISTORY_FILE="$HOME/.zsh_history.db"
#    ZSH_HISTORY_KEYBIND_GET_BY_DIR="^r"
#    ZSH_HISTORY_KEYBIND_GET_ALL="^r^a"
#    ZSH_HISTORY_KEYBIND_SCREEN="^r^r"
#    ZSH_HISTORY_KEYBIND_ARROW_UP="^p"
#    ZSH_HISTORY_KEYBIND_ARROW_DOWN="^n"
#fi

## pack as command and glob patterns (e.g., brace, wildcard, ...)
zplug "Jxck/dotfiles", as:command, use:"bin/{histuniq,color}"

zplug "k4rthik/git-cal", as:command

# Grab binaries from GitHub Releases and "rename-to:" tag
# zplug "junegunn/fzf-bin", from:gh-r, as:command, rename-to:fzf, use:"*${(L)$(uname -s)}*amd64*"
#zplug "junegunn/fzf", as:command, use:"bin/fzf-tmux"
zplug "junegunn/fzf", use:"shell/*.zsh"
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_OPTS='--height 40% --reverse --border --inline-info'

#zplug "jhawthorn/fzy", \
#    as:command, \
#    hook-build:"make && sudo make install"

## Supports oh-my-zsh plugins and the like
zplug "plugins/git",   from:oh-my-zsh
zplug "lib/history", from:oh-my-zsh

zplug "tmuxinator/tmuxinator", use:"completion/*.zsh"

# zsh-syntax-highlighting must be loaded after compinit (defer >1)
zplug "zsh-users/zsh-syntax-highlighting", defer:2

zplug "zuxfoucault/colored-man-pages_mod", use:"*.zsh"


#zplug "unixorn/warhol.plugin.zsh", use:"*.zsh"
#zplug "zpm-zsh/dropbox"

zplug "bobsoppe/zsh-ssh-agent", use:ssh-agent.zsh, from:github
zplug "MichaelAquilina/zsh-you-should-use"

# Can manage local plugins
zplug "~/.zsh", from:local, if:"[[ -d $HOME/.zsh ]]"

# Load theme file
#zplug 'dracula/zsh', as:theme
#zplug 'eendroroy/alien', as:theme
#zplug "sindresorhus/pure", use:"*.zsh", as:theme
zplug 'denysdovhan/spaceship-zsh-theme', as:theme

zplug "escalate/oh-my-zsh-proxy-plugin", if:"[[ -f $HOME/.proxy/http_proxy ]]"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
	echo; zplug install
    fi
fi

#
# End ZPLUG
#


# AT THE VERY END
# Then, source plugins and add commands to $PATH
#zplug load --verbose
zplug load

#if proxy file is there just execture proxy
[[ -f $HOME/.proxy/http_proxy ]] && proxy

### Overide some variables
#
HISTSIZE=30000
SAVEHIST=30000

PATH=${ZPLUG_HOME}/bin:${HOME}/.local/bin:${PATH}
PYTHONPATH=${PYTHONPATH}:$HOME/.local/lib/python/site-packages:$HOME/.local/lib/python2/site-packages
LD_LIBRARY_PATH=${HOME}/.local/lib:${LD_LIBRARY_PATH}
export PATH
export PYTHONPATH
export LD_LIBRARY_PATH
