# Vi mode
bindkey -v
export EDITOR="vim"
setopt extendedglob
setopt nocaseglob
setopt AUTO_CD

# Language
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# XDG
export XDG_CONFIG_HOME="$HOME/.config/"

#
# ZPLUG
#
export ZPLUG_HOME=${HOME}/.zplug

# install zplug if required
if ! [[ -d ${ZPLUG_HOME} ]] then
  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh| zsh
fi

# Load zplug (https://github.com/zplug/zplug)
source ${ZPLUG_HOME}/init.zsh

# FIXME: this line implies the workaround of having .zplug/bin manually included in the PATH
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

#
# ZPLUG
#

zplug "zsh-users/zsh-completions"
zplug "b4b4r07/enhancd", use:init.sh
zplug "plugins/archlinux", from:oh-my-zsh, if:"[[ -f /etc/arch-release ]]"

zplug "lib/history", from:oh-my-zsh
zplug "zdharma/history-search-multi-word"
# zplug "zsh-users/zsh-history-substring-search", defer:3
# if zplug check 'zsh-users/zsh-history-substring-search'; then
#   bindkey -M vicmd 'k' history-substring-search-up
#   bindkey -M vicmd 'j' history-substring-search-down
# fi

zplug "b4b4r07/zsh-vimode-visual", use:"*.zsh", defer:3
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zuxfoucault/colored-man-pages_mod", use:"*.zsh"

zplug "junegunn/fzf", use:"shell/*.zsh"
zplug "atweiden/fzf-extras", use:"fzf-extras.zsh"
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
#export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
export FZF_DEFAULT_OPTS='--height 40% --reverse --border --inline-info'

zplug "k4rthik/git-cal", as:command
zplug "plugins/git",   from:oh-my-zsh

zplug "/usr/lib/ruby/gems/2.4.0/gems/tmuxinator-0.9.0/completion/", from:local

# To Check
#zplug "Jxck/dotfiles", as:command, use:"bin/{histuniq,color}"
#zplug "unixorn/warhol.plugin.zsh", use:"*.zsh"
#zplug "zpm-zsh/dropbox"

zplug "bobsoppe/zsh-ssh-agent", use:ssh-agent.zsh, from:github
zplug "MichaelAquilina/zsh-you-should-use"

# Can manage local plugins
zplug "~/.zsh", from:local, if:"[[ -d $HOME/.zsh ]]"

# Load theme file
#zplug "sindresorhus/pure", use:"*.zsh", as:theme
zplug 'denysdovhan/spaceship-zsh-theme', as:theme

zplug "escalate/oh-my-zsh-proxy-plugin", if:"[[ -f $HOME/.proxy/http_proxy ]]"


# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

#
# End ZPLUG
#


# AT THE VERY END
# Then, source plugins and add commands to $PATH
#zplug load --verbose
zplug load

#if proxy file is there just execute proxy
[[ -f $HOME/.proxy/http_proxy ]] && proxy

### Overide and define some variables
HISTSIZE=30000
SAVEHIST=30000

PATH=${ZPLUG_HOME}/bin:${HOME}/.local/bin:${PATH}
PYTHONPATH=${PYTHONPATH}:$HOME/.local/lib/python/site-packages:$HOME/.local/lib/python2/site-packages
LD_LIBRARY_PATH=${HOME}/.local/lib:${LD_LIBRARY_PATH}
export PATH
export PYTHONPATH
export LD_LIBRARY_PATH
